import os
import re
import html
import subprocess
import logging
from datetime import datetime
from .logs_helper import log_path

logger = logging.getLogger(__name__)


def _md_to_html_body(content: str) -> str:
    """Minimal markdown -> HTML conversion (no external deps)."""
    lines = content.split("\n")
    out = []
    in_code = False

    for line in lines:
        if line.startswith("```"):
            if in_code:
                out.append("</pre>")
                in_code = False
            else:
                lang = html.escape(line[3:].strip())
                out.append(f'<pre class="code" data-lang="{lang}">')
                in_code = True
            continue

        if in_code:
            out.append(html.escape(line))
            continue

        line = html.escape(line)
        line = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', line)
        line = re.sub(r'`(.*?)`', r'<code>\1</code>', line)

        if line.startswith("### "):
            out.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            out.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            out.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("- ") or line.startswith("* "):
            out.append(f"<li>{line[2:]}</li>")
        elif not line.strip():
            out.append("<br>")
        else:
            out.append(f"<p>{line}</p>")

    return "\n".join(out)


def run(title: str, content: str, generate_pdf: bool = False) -> str:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    md_path = log_path(f"report_{ts}.md")
    html_path = log_path(f"report_{ts}.html")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(f"# {title}\n\n_Generated by Phantom | {ts}_\n\n{content}")

    safe_title = html.escape(title)
    body = _md_to_html_body(content)
    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Phantom \u2014 {safe_title}</title>
  <style>
    body  {{ font-family: 'Courier New', monospace; background:#0d1117; color:#c9d1d9;
             max-width:960px; margin:40px auto; padding:0 24px; line-height:1.6; }}
    h1   {{ color:#f85149; border-bottom:2px solid #f85149; padding-bottom:10px; }}
    h2   {{ color:#58a6ff; background:#161b22; padding:8px 14px;
             border-left:4px solid #f85149; margin-top:30px; }}
    h3   {{ color:#79c0ff; margin-top:20px; }}
    pre  {{ background:#161b22; border:1px solid #30363d; padding:16px;
             border-radius:6px; overflow-x:auto; color:#a5d6ff; }}
    code {{ background:#161b22; padding:2px 6px; border-radius:3px; color:#ff7b72; }}
    li   {{ margin:4px 0; }}
    strong {{ color:#f85149; }}
    .meta {{ color:#6e7681; font-size:.9em; margin-bottom:28px; border-bottom:1px solid #21262d; padding-bottom:12px; }}
    .banner {{ background:#161b22; border:1px solid #30363d; border-radius:6px;
               padding:12px 16px; margin-bottom:24px; color:#58a6ff; letter-spacing:2px; }}
  </style>
</head>
<body>
  <div class="banner">[ PHANTOM ETHICAL REDTEAM \u2014 MISSION REPORT ]</div>
  <h1>{safe_title}</h1>
  <div class="meta">Generated: {ts} | Phantom Ethical RedTeam</div>
  {body}
</body>
</html>"""

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_doc)

    result = f"Report saved:\n  Markdown : {md_path}\n  HTML     : {html_path}"

    if generate_pdf:
        pdf_path = log_path(f"report_{ts}.pdf")
        try:
            subprocess.run(
                ["wkhtmltopdf", "--quiet", html_path, pdf_path],
                capture_output=True, timeout=60,
            )
            if os.path.exists(pdf_path):
                result += f"\n  PDF      : {pdf_path}"
            else:
                result += "\n  PDF      : wkhtmltopdf ran but produced no output"
        except FileNotFoundError:
            result += "\n  PDF      : skipped (wkhtmltopdf not installed)"
        except Exception as e:
            result += f"\n  PDF      : failed ({e})"

    logger.info("Report generated: %s", md_path)
    return result


TOOL_SPEC = {
    "name": "generate_report",
    "description": (
        "Generate a formatted mission report (Markdown + HTML, optional PDF). "
        "Call at the end of the mission, before cleanup_temp, "
        "with the full executive summary, findings, PoC, and recommendations."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "description": "Report title, e.g. 'Pentest Report \u2014 target.com \u2014 2026-03-18'",
            },
            "content": {
                "type": "string",
                "description": "Full report body in Markdown format",
            },
            "generate_pdf": {
                "type": "boolean",
                "description": "Generate PDF via wkhtmltopdf (default false)",
            },
        },
        "required": ["title", "content"],
    },
}
