# agent/main.py
import os
import sys
import yaml
import logging
from pathlib import Path

# Ensure agent/ is on sys.path
sys.path.insert(0, str(Path(__file__).parent))

from agent_client import AgentClient
from providers import PROVIDERS

ROOT = Path(__file__).parent.parent

# Ensure logs directory exists (first run or fresh clone)
(ROOT / "logs").mkdir(exist_ok=True)

logging.basicConfig(
    filename=ROOT / "logs" / "agent.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)

# CONFIG
with open(ROOT / "config.yaml") as f:
    config = yaml.safe_load(f)

with open(ROOT / "prompts" / "system_prompt.txt") as f:
    SYSTEM_PROMPT = f.read()

scope_path = ROOT / config.get("scope_file", "scopes/current_scope.md")
SCOPE = scope_path.read_text() if scope_path.exists() else ""

# Reject placeholder scope
if not SCOPE.strip() or "https://xxx" in SCOPE:
    print("❌ Scope invalide ou placeholder détecté. Renseigne scopes/current_scope.md avec une cible autorisée.")
    sys.exit(1)

# Load API key from .env file if present (generated by install.sh / install.ps1)
env_file = ROOT / ".env"
if env_file.exists():
    for line in env_file.read_text().splitlines():
        if "=" in line and not line.startswith("#"):
            k, _, v = line.partition("=")
            os.environ.setdefault(k.strip(), v.strip())

provider = config.get("provider", "anthropic").lower()
print("======================================")
print("  🚀 Phantom – Ethical RedTeam")
print(f"  Provider : {provider.upper()}")
print(f"  Model    : {config.get('model', 'default')}")
print(f"  Mode     : {'AUTONOMOUS' if config.get('autonomous', False) else 'Interactive'}")
print(f"  Scope    : {SCOPE.splitlines()[0]}")
print("======================================\n")

client = AgentClient(config=config)

messages = [
    {
        "role": "user",
        "content": (
            f"Authorized scope :\n{SCOPE}\n\n"
            "START THE MISSION IN AUTONOMOUS MODE. Think step by step, "
            "correct yourself, use the tools in sequence. "
            "Finish only with === MISSION COMPLETE === when it's done."
        ),
    }
]

turn = 0
max_turns = config.get("max_autonomous_turns", 50)

while turn < max_turns:
    try:
        messages = client.think(messages=messages, system_prompt=SYSTEM_PROMPT)

        # Extract text from last assistant message
        last_assistant = next(
            (m for m in reversed(messages) if m.get("role") == "assistant"), None
        )
        assistant_text = ""
        if last_assistant:
            content = last_assistant["content"]
            if isinstance(content, list):
                assistant_text = " ".join(
                    b.get("text", "") for b in content if b.get("type") == "text"
                )
            else:
                assistant_text = str(content)

        if "=== MISSION COMPLETE ===" in assistant_text:
            print("\n🎯 MISSION COMPLETE BY PHANTOM !")
            print(assistant_text.split("=== MISSION COMPLETE ===")[-1])
            break

        turn += 1

        if turn % config.get("pause_every_n_turns", 10) == 0:
            print(f"\n⏸️  Pause after {turn} steps.")
            cmd = input("Entrée = continue | 'stop' = stop | 'report' = force report : ").strip().lower()
            if cmd == "stop":
                break
            if cmd == "report":
                messages.append({"role": "user", "content": "Generate final report now."})

    except KeyboardInterrupt:
        print("\n👋 Mission aborted by user.")
        break
    except Exception as e:
        logging.error(f"Error : {e}")
        print(f"Erreur : {e}")
        break

print("Phantom stopped successfully.")
